# Site
name: 'DataViz.Tools'
description: 'The premier curated collection of data visualization tools and resources'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
avatar: 'assets/images/sal.jpg'
disqus: 'demowebsite'
email: 'carl@dataviz.tools'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]